services:
  docs:
    networks: [FreeForUs]
    build:
      context: .
      dockerfile: Dockerfile
    image: FreeForUs-docs
    container_name: docs
    restart: unless-stopped
    ports:
      - '4173:80'

networks:
  FreeForUs:
